root_dir = "."

[os.unix]
dev = ["DEBUG=2 python3 thinkledger/main.py"]
frontend = [
"npx tailwindcss -i ./static/style/input.css -o ./static/style/style.css --minify",
"npm run minify"
]
prod = []
test = []

[os.windows]
dev = []
prod = []
test = []

[exclude]
dir = [".git", "__pycache__", "mypy_cache",".git", "node_modules", ".vscode", ".venv"]
file = []
ext = ["toml"]
