root_dir = "."

[os.unix]
dev = ["DEBUG=2 python3 -m thinkledger"]
prod = []
test = []

[os.windows]
dev = []
prod = []
test = []

[exclude]
dir = [".git", "__pycache__", "mypy_cache"]
file = []
ext = ["toml"]
