root_dir = "."

[os.unix]
fd = ["cd frontend && npm run dev" ]
ext = ["cd extension && npm run build"]
test = []

[os.windows]
fd = ["cd frontend && npm run dev" ]
ext = ["cd extension && npm run build"]
prod = []
test = []

[exclude]
dir = [
    ".git",
    "node_modules",
    "__pycache__",
    ".ruff_cache",
    ".mypy_cache",
    ".vscode",
    ".venv",]
file = []
ext = ["toml"]
