root_dir = "."

[os.unix]
dev = [
    "ngrok http --url=admittedly-adequate-scorpion.ngrok-free.app 3000",
    "DEBUG=2 python3 -m thinkledger"
    ]
prod = []
test = []

[os.windows]
dev = []
prod = []
test = []

[exclude]
dir = [
    ".git",
    "node_modules",
    "__pycache__",
    ".ruff_cache",
    ".mypy_cache",
    ".vscode",
    ".venv",]
file = []
ext = ["toml"]
